#!/usr/bin/env bash

./node_modules/.bin/grpc_tools_node_protoc \
  --plugin=protoc-gen-ts_proto=./node_modules/.bin/protoc-gen-ts_proto \
  --ts_proto_out=./src/proto \
  --ts_proto_opt=env=node,importSuffix='.js',exportCommonSymbols=false,esModuleInterop=true,forceLong=number,unrecognizedEnum=false,snakeToCamel=false,outputServices=grpc-js,useExactTypes=false,stringEnums=true,enumsAsLiterals=true,outputPartialMethods=false\
  --proto_path=./proto \
  ./proto/*
  